trunk: master
name: autostaging
branches:
  - auto-gps
  - app-buttons # Emord 7/30
  - subtree-merge-forms-cases
#  - add-build-ui
  - hq-dropdown # sravan 5/7
  - refactor-domain-copy2  # Brian 5/20
#  - vellum-requirejs+use-django-compressor
#  - use-django-compressor # bb 7/1
  - logos # Nick P 5/28
  - switch_to_site_code # tw 6/17
  - vellum-requirejs # Daniel 6/12
  - schedule # SK 7/17
#  - emwf-refactor  # Ethan 7/25
  - real-project-spaces # Nick P 7/27
  - closecase  # SK 7/28
  - basic-auth
  - archive-to-deactivate  # cz 7/30
submodules:
  submodules/couchlog-src:
    branches:
      - static-tags # Nick P 5/20
  submodules/django-soil-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/formdesigner:
#    branches:
#      - develop-staging # Daniel 6/12 (major refactor + itemsets?)
#      - universal-analytics-upgrade # Nick P 7/8
  submodules/formtranslate-src:
    branches:
      - static-tags # Nick P 5/20
  submodules/touchforms-src:
    branches:
      - static-tags # Nick P 5/20
#  submodules/dimagi-utils-src:
#    branches:
#      - json_response-status
  submodules/pillowtop-src:
    branches:
      - reset # SK 7/28
